export const emailsMockData = {
  success: true,
  message: 'getAllSequenceEmailsApi executed successfully',
  result: {
    numOfPages: 1,
    data: [
      {
        _id: '5ebeb9e9-5991-4897-82a2-2e53684f321e',
        prospect_name: 'SGR_UWA T2',
        prospect_email: 'sanjugr.unitedweare@gmail.com',
        prospect_phone_number: '12345678902',
        // message: {
        //   subject: 'Exlusive offer to sign up for sanjugr.unitedweare@gmail.com',
        //   body: "<p>To: <b> sanjugr.unitedweare@gmail.com </b></p><p>Dear User</p> <p>Please don't miss the opportunity to sign up for our exclusive offer</p> <p>Thanks</p> <p>Ex Team</p>",
        // },
        status: 'sent',
        scheduled_time: 1713535140000,
        created_on: 1713534559099,
        sender_email: 'sanjay.gowdru.r@gmail.com',
      },
      {
        _id: 'd26cbb20-5829-42a7-aafa-f44df95022a7',
        prospect_name: 'SGR_UWA_1 T3',
        prospect_email: 'sanjugr.unitedweare_1@gmail.com',
        prospect_phone_number: '12345678902',
        // message: {
        //   subject: 'Exlusive offer to sign up for sanjugr.unitedweare_1@gmail.com',
        //   body: "<p>To: <b> sanjugr.unitedweare_1@gmail.com </b></p><p>Dear User</p> <p>Please don't miss the opportunity to sign up for our exclusive offer</p> <p>Thanks</p> <p>Ex Team</p>",
        // },
        status: 'bounced',
        scheduled_time: 1713535140000,
        created_on: 1713534559099,
        sender_email: 'sanjay.gowdru.r@gmail.com',
      },
      {
        _id: 'a9ef0a63-adc5-4807-ba8a-56e78d179905',
        prospect_name: 'SGR_7022 T1',
        prospect_email: 'sanjugr7022@gmail.com',
        prospect_phone_number: '12345678901',
        // message: {
        //   subject: 'Exlusive offer to sign up for sanjugr7022@gmail.com',
        //   body: "<p>To: <b> sanjugr7022@gmail.com </b></p><p>Dear User</p> <p>Please don't miss the opportunity to sign up for our exclusive offer</p> <p>Thanks</p> <p>Ex Team</p>",
        // },
        status: 'sent',
        scheduled_time: 1713535140000,
        created_on: 1713534559098,
        sender_email: 'sanjay.gowdru.r@gmail.com',
      },
      {
        _id: '3eb97287-6323-4042-aa0b-e578a866a2b0',
        prospect_name: 'SGR_UWA_1 T3',
        prospect_email: 'sanjugr.unitedweare_1@gmail.com',
        prospect_phone_number: '12345678902',
        // message: {
        //   subject: 'Exlusive offer to sign up for sanjugr.unitedweare_1@gmail.com',
        //   body: "<p>To: <b> sanjugr.unitedweare_1@gmail.com </b></p><p>Dear User</p> <p>Please don't miss the opportunity to sign up for our exclusive offer</p> <p>Thanks</p> <p>Ex Team</p>",
        // },
        status: 'bounced',
        scheduled_time: 1713496380000,
        created_on: 1713495332913,
        sender_email: 'sanjay.gowdru.r@gmail.com',
      },
      {
        _id: 'b18f205e-a38b-4b03-8035-07495dcd869d',
        prospect_name: 'SGR_UWA T2',
        prospect_email: 'sanjugr.unitedweare@dom1.com',
        prospect_phone_number: '12345678902',
        // message: {
        //   subject: 'Exlusive offer to sign up for sanjugr.unitedweare@gmail.com',
        //   body: "<p>To: <b> sanjugr.unitedweare@gmail.com </b></p><p>Dear User</p> <p>Please don't miss the opportunity to sign up for our exclusive offer</p> <p>Thanks</p> <p>Ex Team</p>",
        // },
        status: 'sent',
        scheduled_time: 1713496380000,
        created_on: 1713495332913,
        sender_email: 'sanjay.gowdru.r@gmail.com',
      },
      {
        _id: 'a90e78d2-b54e-4581-9cbe-7aeb87e03ae2',
        prospect_name: 'SGR_7022 T1',
        prospect_email: 'sanjugr7022@dom1.com',
        prospect_phone_number: '12345678901',
        // message: {
        //   subject: 'Exlusive offer to sign up for sanjugr7022@gmail.com',
        //   body: "<p>To: <b> sanjugr7022@gmail.com </b></p><p>Dear User</p> <p>Please don't miss the opportunity to sign up for our exclusive offer</p> <p>Thanks</p> <p>Ex Team</p>",
        // },
        status: 'sent',
        scheduled_time: 1713496380000,
        created_on: 1713495332912,
        sender_email: 'sanjay.gowdru.r@gmail.com',
      },
    ],
    headers: {
      _id: {
        label: 'ID',
        type: 'string',
        hidden: true,
        order: 0,
      },
      prospect_name: {
        label: 'Prospect Name',
        type: 'string',
        order: 1,
      },
      prospect_email: {
        label: 'Prospect Email',
        type: 'string',
        order: 2,
      },
      prospect_phone_number: {
        label: 'Prospect Phone Number',
        type: 'string',
        order: 3,
      },
      // message: {
      //   label: 'Message',
      //   type: 'draft',
      //   order: 4,
      // },
      status: {
        label: 'Status',
        type: 'chip',
        values: ['pending', 'sent', 'bounced'],
        order: 5,
      },
      sender_email: {
        label: 'Sender Email',
        type: 'string',
        order: 6,
      },
      scheduled_time: {
        label: 'Scheduled Time',
        type: 'datetime_millis',
        order: 7,
      },
      created_on: {
        label: 'Created On',
        type: 'datetime_millis',
        order: 8,
      },
    },
  },
};

export const emailsMockData = {
  success: true,
  message: 'getAllSequenceEmailsApi executed successfully',
  result: {
    numOfPages: 1,
    data: [
      {
        _id: '5ebeb9e9-5991-4897-82a2-2e53684f321e',
        prospect_name: 'SGR_UWA T2',
        prospect_email: 'sanjugr.unitedweare@gmail.com',
        prospect_phone_number: '12345678902',
        // message: {
        //   subject: 'Exlusive offer to sign up for sanjugr.unitedweare@gmail.com',
        //   body: "<p>To: <b> sanjugr.unitedweare@gmail.com </b></p><p>Dear User</p> <p>Please don't miss the opportunity to sign up for our exclusive offer</p> <p>Thanks</p> <p>Ex Team</p>",
        // },
        status: 'sent',
        scheduled_time: 1713535140000,
        created_on: 1713534559099,
        sender_email: 'sanjay.gowdru.r@gmail.com',
      },
      {
        _id: 'd26cbb20-5829-42a7-aafa-f44df95022a7',
        prospect_name: 'SGR_UWA_1 T3',
        prospect_email: 'sanjugr.unitedweare_1@gmail.com',
        prospect_phone_number: '12345678902',
        // message: {
        //   subject: 'Exlusive offer to sign up for sanjugr.unitedweare_1@gmail.com',
        //   body: "<p>To: <b> sanjugr.unitedweare_1@gmail.com </b></p><p>Dear User</p> <p>Please don't miss the opportunity to sign up for our exclusive offer</p> <p>Thanks</p> <p>Ex Team</p>",
        // },
        status: 'bounced',
        scheduled_time: 1713535140000,
        created_on: 1713534559099,
        sender_email: 'sanjay.gowdru.r@gmail.com',
      },
      {
        _id: 'a9ef0a63-adc5-4807-ba8a-56e78d179905',
        prospect_name: 'SGR_7022 T1',
        prospect_email: 'sanjugr7022@gmail.com',
        prospect_phone_number: '12345678901',
        // message: {
        //   subject: 'Exlusive offer to sign up for sanjugr7022@gmail.com',
        //   body: "<p>To: <b> sanjugr7022@gmail.com </b></p><p>Dear User</p> <p>Please don't miss the opportunity to sign up for our exclusive offer</p> <p>Thanks</p> <p>Ex Team</p>",
        // },
        status: 'sent',
        scheduled_time: 1713535140000,
        created_on: 1713534559098,
        sender_email: 'sanjay.gowdru.r@gmail.com',
      },
      {
        _id: '3eb97287-6323-4042-aa0b-e578a866a2b0',
        prospect_name: 'SGR_UWA_1 T3',
        prospect_email: 'sanjugr.unitedweare_1@gmail.com',
        prospect_phone_number: '12345678902',
        // message: {
        //   subject: 'Exlusive offer to sign up for sanjugr.unitedweare_1@gmail.com',
        //   body: "<p>To: <b> sanjugr.unitedweare_1@gmail.com </b></p><p>Dear User</p> <p>Please don't miss the opportunity to sign up for our exclusive offer</p> <p>Thanks</p> <p>Ex Team</p>",
        // },
        status: 'bounced',
        scheduled_time: 1713496380000,
        created_on: 1713495332913,
        sender_email: 'sanjay.gowdru.r@gmail.com',
      },
      {
        _id: 'b18f205e-a38b-4b03-8035-07495dcd869d',
        prospect_name: 'SGR_UWA T2',
        prospect_email: 'sanjugr.unitedweare@dom1.com',
        prospect_phone_number: '12345678902',
        // message: {
        //   subject: 'Exlusive offer to sign up for sanjugr.unitedweare@gmail.com',
        //   body: "<p>To: <b> sanjugr.unitedweare@gmail.com </b></p><p>Dear User</p> <p>Please don't miss the opportunity to sign up for our exclusive offer</p> <p>Thanks</p> <p>Ex Team</p>",
        // },
        status: 'sent',
        scheduled_time: 1713496380000,
        created_on: 1713495332913,
        sender_email: 'sanjay.gowdru.r@gmail.com',
      },
      {
        _id: 'a90e78d2-b54e-4581-9cbe-7aeb87e03ae2',
        prospect_name: 'SGR_7022 T1',
        prospect_email: 'sanjugr7022@dom1.com',
        prospect_phone_number: '12345678901',
        // message: {
        //   subject: 'Exlusive offer to sign up for sanjugr7022@gmail.com',
        //   body: "<p>To: <b> sanjugr7022@gmail.com </b></p><p>Dear User</p> <p>Please don't miss the opportunity to sign up for our exclusive offer</p> <p>Thanks</p> <p>Ex Team</p>",
        // },
        status: 'sent',
        scheduled_time: 1713496380000,
        created_on: 1713495332912,
        sender_email: 'sanjay.gowdru.r@gmail.com',
      },
    ],
    headers: {
      _id: {
        label: 'ID',
        type: 'string',
        hidden: true,
        order: 0,
      },
      prospect_name: {
        label: 'Prospect Name',
        type: 'string',
        order: 1,
      },
      prospect_email: {
        label: 'Prospect Email',
        type: 'string',
        order: 2,
      },
      prospect_phone_number: {
        label: 'Prospect Phone Number',
        type: 'string',
        order: 3,
      },
      // message: {
      //   label: 'Message',
      //   type: 'draft',
      //   order: 4,
      // },
      status: {
        label: 'Status',
        type: 'chip',
        values: ['pending', 'sent', 'bounced'],
        order: 5,
      },
      sender_email: {
        label: 'Sender Email',
        type: 'string',
        order: 6,
      },
      scheduled_time: {
        label: 'Scheduled Time',
        type: 'datetime_millis',
        order: 7,
      },
      created_on: {
        label: 'Created On',
        type: 'datetime_millis',
        order: 8,
      },
    },
  },
};
