import mongoose from "mongoose";

const Schema = mongoose.Schema;

const SequenceStepSchema = new Schema({
    _id: String,
    sequence: { type: String, ref: "sequence" },
    account: { type: Schema.Types.ObjectId, ref: "account" },
    created_by: { type: Schema.Types.ObjectId, ref: "User" },

    /*
    type: "email" or "linkedin_connection_request"
    */
    type: String,
    subject: String,
    body: String,
    // later we will support draft_type: "fixed" or "hybrid" or "ai_generated". For now, it is only "ai_generated"
    // * 18Jan2025 Update: we will support another type called "none". It is only for linkedin_connection_request. This means that the request needs to be sent without any message.
    draft_type: { type: String, default: "ai_generated" },
    /*
    time_of_dispatch: {
            type: "from_prospect_added_time",
            value: { time_value: 1, time_unit: "day" },
        }
    */
    time_of_dispatch: {},
    active: { type: Boolean, default: true },
    order: Number,

    is_prospects_generation_completed: { type: Boolean, default: false },
    prospects_generation_estimation_date: Date,

    /*
     * Added 'activities' on 23rd July 2024
     * Initially this will be empty.
     * When prospect messages are generated by AI server, we will add object {type:"prospect_messages_added", time: DateIsoString, txid} in this array.
     * If we were to add additional prospects, we will add object {type:"prospect_messages_added", time: DateIsoString, txid} again.
     *  - This is not yet implemented. But we have made provision for this now, by making this an array.
     */
    activities: [],

    created_on: { type: Date, default: Date.now },
    updated_on: { type: Date, default: Date.now },
});

export const SequenceStep = mongoose.model(
    "sequence.step",
    SequenceStepSchema,
    "sequence.step"
);
