// clear
export const CLEAR_STORE = 'CLEAR_STORE';
export const CLEAR_CONFIG_REDUCER = 'CLEAR_CONFIG_REDUCER';
export const CLEAR_USER_REDUCER = 'CLEAR_USER_REDUCER';
export const CLEAR_INTEGRATIONS_REDUCER = 'CLEAR_INTEGRATIONS_REDUCER';
export const CLEAR_DATA_REDUCER = 'CLEAR_DATA_REDUCER';

// configReducer.js
export const SET_THEME = 'SET_THEME';
export const SET_LOADING = 'SET_LOADING';
export const SET_SHOW_SWITCH_ACCOUNTS = 'SET_SHOW_SWITCH_ACCOUNTS';

// userReducer.js
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const UPDATE_GOOGLE_CALENDAR_SYNC_TOKEN = 'UPDATE_GOOGLE_CALENDAR_SYNC_TOKEN';
export const UPDATE_TRIAL_EXPIRY = 'UPDATE_TRIAL_EXPIRY';
export const SWITCH_ACCOUNT = 'SWITCH_ACCOUNT';
export const UPDATE_GOOGLE_TOKEN = 'UPDATE_GOOGLE_TOKEN';
export const UPDATE_ACTIVE_EMAILS = 'UPDATE_ACTIVE_EMAILS';
export const UPDATE_DEVICE_INFO = 'UPDATE_DEVICE_INFO';
export const SET_USER_ORG_INFO = 'SET_USER_ORG_INFO';
export const SET_USER_TOKENS = 'SET_USER_TOKENS';
export const SET_USER_WORKSPACE = 'SET_USER_WORKSPACE';
export const SET_DEV_FEATURE = 'SET_DEV_FEATURE';

// dataReducer.js
export const SET_DATA_QUEUES = 'SET_DATA_QUEUES';
export const SET_DATA_OPENLINKS = 'SET_DATA_OPENLINKS';
export const SET_DATA_ROBINLINKS = 'SET_DATA_ROBINLINKS';
export const SET_DATA_COLLECTIVELINKS = 'SET_DATA_COLLECTIVELINKS';
export const SET_DATA_ROUTINGS = 'SET_DATA_ROUTINGS';
export const SET_ACTIVE_ROUTING = 'SET_ACTIVE_ROUTING';
export const SET_DATA_CHATBOTS = 'SET_DATA_CHATBOTS';
export const SET_DATA_CHATBOT_EXPERIENCES = 'SET_DATA_CHATBOT_EXPERIENCES';
export const SET_DATA_ACCOUNT_USERS = 'SET_DATA_ACCOUNT_USERS';
export const SET_DATA_ACCOUNT_TEAMS = 'SET_DATA_ACCOUNT_TEAMS';
export const SET_DATA_ROUTING_BUILDERS = 'SET_DATA_ROUTING_BUILDERS';
export const SET_DATA_MY_CONFIGURATION = 'SET_DATA_MY_CONFIGURATION';
export const SET_DATA_ANALYTICS_DATA = 'SET_DATA_ANALYTICS_DATA';
export const SET_DATA_QUALIFIED = 'SET_DATA_QUALIFIED';
export const SET_DATA_DISQUALIFIED = 'SET_DATA_DISQUALIFIED';
export const SET_DATA_LINKS_SUMMARY = 'SET_DATA_LINKS_SUMMARY';
export const SET_DATA_MESSAGE_TEMPLATES = 'SET_DATA_MESSAGE_TEMPLATES';

// integrationReducer.js
export const SET_HUBSPOT = 'SET_HUBSPOT';
export const SET_SALESFORCE = 'SET_SALESFORCE';
export const SET_ZOHO = 'SET_ZOHO';
export const SET_ZOOM = 'SET_ZOOM';
